/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.gnu.monedero.gui;

import java.awt.Color;
import javax.swing.JFrame;
import org.gnu.monedero.certificado.Reportes;
import org.gnu.monedero.entity.Estudiante;
import org.gnu.monedero.utils.Config;
import org.gnu.monedero.utils.Etiqueta;

/**
 *
 * @author dizurieta
 */
public class Certificado extends javax.swing.JFrame {
    private Estudiante estudiante;
    private Etiqueta etiqueta;
    private Reportes reportes ;

    /**
     * Creates new form Detalle
     * @param estudiante
     */
    public Certificado(Estudiante estudiante) {
        this.estudiante = estudiante;
        reportes = new Reportes();
        initComponents();
        initComponentsOverride();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salirJButton = new javax.swing.JButton();
        cjJButton = new javax.swing.JButton();
        cmJButton = new javax.swing.JButton();
        ciJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(getUndecorated());
        getContentPane().setLayout(null);

        salirJButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        salirJButton.setText("CANCELAR");
        salirJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salirJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(salirJButton);
        salirJButton.setBounds(610, 690, 180, 40);

        cjJButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cjJButton.setText("CERTIFICADO DE CAMBIO DE JORNADA");
        cjJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cjJButton);
        cjJButton.setBounds(480, 560, 470, 50);

        cmJButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cmJButton.setText("CERTIFICADO BAJA DE CUPO");
        cmJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cmJButton);
        cmJButton.setBounds(480, 440, 470, 50);

        ciJButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ciJButton.setText("CERTIFICADO LEGALMENTE MATRICULADO");
        ciJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ciJButton);
        ciJButton.setBounds(450, 340, 520, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/gnu/monedero/gui/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 1510, 900);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salirJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirJButtonActionPerformed
        // TODO add your handling code here:

        new Verificacion().setVisible(true);
        dispose();
    }//GEN-LAST:event_salirJButtonActionPerformed

    private void ciJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciJButtonActionPerformed
        // TODO add your handling code here:
        etiqueta =  new Etiqueta(this, true, Config.getValue("inscripcion_dolar"), Config.getValue("inscripcion_dolar_message"));
        etiqueta.setLocationRelativeTo(null);
        etiqueta.setVisible(true);
        if(etiqueta.status){
            reportes.imprimir(estudiante.getV_cedula(), "inscripcion");
        }
        new Verificacion().setVisible(true);
        etiqueta.monedero.status = false;
        etiqueta.dispose();
        dispose();
    }//GEN-LAST:event_ciJButtonActionPerformed

    private void cmJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmJButtonActionPerformed
        // TODO add your handling code here:
        etiqueta =  new Etiqueta(this, true, Config.getValue("matricula_dolar"), Config.getValue("matricula_dolar_message"));
        etiqueta.setLocationRelativeTo(null);
        etiqueta.setVisible(true);
        if(etiqueta.status){
            reportes.imprimir(estudiante.getV_cedula(), "matricula");
        }
        new Verificacion().setVisible(true);
        etiqueta.monedero.status = false;
        etiqueta.dispose();
        dispose();
    }//GEN-LAST:event_cmJButtonActionPerformed

    private void cjJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjJButtonActionPerformed
        // TODO add your handling code here:
        etiqueta =  new Etiqueta(this, true, Config.getValue("jornada_dolar"), Config.getValue("jornada_dolar_message"));
        etiqueta.setLocationRelativeTo(null);
        etiqueta.setVisible(true);
        if(etiqueta.status){
            reportes.imprimir(estudiante.getV_cedula(), "jornada");
        }
        new Verificacion().setVisible(true);
        etiqueta.monedero.status = false;
        etiqueta.dispose();
        dispose();
    }//GEN-LAST:event_cjJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Certificado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Certificado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Certificado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Certificado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Estudiante estudiante = new Estudiante("fddfdsfsdf","dsasd", "dsfdfdsfsdfsdf", "ddasdasdasdasdasdasdasdasdasdsadasdfdsfdsfdsfsdf","sdfdsfdsfsdfdsfdsfsdf", "sdfsdfsdf", "sdfdsfdfsd");
                new Certificado(estudiante).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ciJButton;
    private javax.swing.JButton cjJButton;
    private javax.swing.JButton cmJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton salirJButton;
    // End of variables declaration//GEN-END:variables

    private void initComponentsOverride() {
       this.setExtendedState(JFrame.MAXIMIZED_BOTH);
       this.setLocationRelativeTo(null);
       this.getContentPane().setBackground(Color.WHITE);
       this.setIconImage(Config.iconDefault());
      
       
    }
    
    private boolean getUndecorated(){
        return Boolean.valueOf(Config.getValue("undecorated"));
    }
}
