/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.gnu.monedero.gui;

import java.awt.Color;
import javax.swing.JFrame;
import org.gnu.monedero.certificado.Reportes;
import org.gnu.monedero.entity.Estudiante;
import org.gnu.monedero.utils.Config;
import org.gnu.monedero.utils.Etiqueta;
import org.gnu.monedero.utils.Monedero;

/**
 *
 * @author dizurieta
 */
public class Detalles extends javax.swing.JFrame {
    private Estudiante estudiante;
    private Etiqueta etiqueta;
    Reportes reportes ;

    /**
     * Creates new form Detalle
     * @param estudiante
     */
    public Detalles(Estudiante estudiante) {
        this.estudiante = estudiante;
        reportes = new Reportes();
        initComponents();
        initComponentsOverride();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salirJButton = new javax.swing.JButton();
        calificacionesJButton = new javax.swing.JButton();
        certificadoJButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        apellidoJTextField = new javax.swing.JTextField();
        nombreJTextField = new javax.swing.JTextField();
        identidadJTextField = new javax.swing.JTextField();
        carreraJTextField = new javax.swing.JTextField();
        jornadaJTextField = new javax.swing.JTextField();
        paraleloJTextField = new javax.swing.JTextField();
        semestreJTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(getUndecorated());
        getContentPane().setLayout(null);

        salirJButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        salirJButton.setText("CANCELAR");
        salirJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salirJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(salirJButton);
        salirJButton.setBounds(910, 650, 260, 40);

        calificacionesJButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        calificacionesJButton.setText("CALIFICACIONES");
        calificacionesJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calificacionesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calificacionesJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(calificacionesJButton);
        calificacionesJButton.setBounds(536, 650, 270, 40);

        certificadoJButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        certificadoJButton.setText("CERTIFICADO");
        certificadoJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        certificadoJButton.setPreferredSize(new java.awt.Dimension(213, 37));
        certificadoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certificadoJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(certificadoJButton);
        certificadoJButton.setBounds(190, 650, 260, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("JORNADA :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(358, 570, 180, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("PARALELO :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(344, 520, 190, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("SEMESTRE :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(345, 480, 190, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("CARRERA :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(340, 440, 190, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("IDENTIDAD :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(332, 400, 200, 29);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("APELLIDO :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(341, 360, 190, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("NOMBRE :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(352, 320, 180, 29);

        apellidoJTextField.setEditable(false);
        apellidoJTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        apellidoJTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        apellidoJTextField.setOpaque(false);
        getContentPane().add(apellidoJTextField);
        apellidoJTextField.setBounds(520, 360, 530, 31);

        nombreJTextField.setEditable(false);
        nombreJTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nombreJTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nombreJTextField.setOpaque(false);
        getContentPane().add(nombreJTextField);
        nombreJTextField.setBounds(520, 320, 530, 31);

        identidadJTextField.setEditable(false);
        identidadJTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        identidadJTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        identidadJTextField.setOpaque(false);
        identidadJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identidadJTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(identidadJTextField);
        identidadJTextField.setBounds(520, 400, 530, 31);

        carreraJTextField.setEditable(false);
        carreraJTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        carreraJTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        carreraJTextField.setOpaque(false);
        getContentPane().add(carreraJTextField);
        carreraJTextField.setBounds(520, 440, 870, 31);

        jornadaJTextField.setEditable(false);
        jornadaJTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jornadaJTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jornadaJTextField.setOpaque(false);
        jornadaJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jornadaJTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(jornadaJTextField);
        jornadaJTextField.setBounds(530, 570, 430, 31);

        paraleloJTextField.setEditable(false);
        paraleloJTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        paraleloJTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        paraleloJTextField.setOpaque(false);
        paraleloJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paraleloJTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(paraleloJTextField);
        paraleloJTextField.setBounds(530, 510, 430, 31);

        semestreJTextField.setEditable(false);
        semestreJTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        semestreJTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        semestreJTextField.setOpaque(false);
        getContentPane().add(semestreJTextField);
        semestreJTextField.setBounds(520, 480, 430, 31);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/gnu/monedero/gui/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1510, 910);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salirJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirJButtonActionPerformed
        // TODO add your handling code here:
        
        new Verificacion().setVisible(true);
        dispose();
    }//GEN-LAST:event_salirJButtonActionPerformed

    private void certificadoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certificadoJButtonActionPerformed
        // TODO add your handling code here:
        new Certificado(estudiante).setVisible(true);
        dispose();
    }//GEN-LAST:event_certificadoJButtonActionPerformed

    private void calificacionesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calificacionesJButtonActionPerformed
        // TODO add your handling code here:
        
        etiqueta =  new Etiqueta(this, true, Config.getValue("notas_dolar"), Config.getValue("notas_dolar_message"));
        etiqueta.setLocationRelativeTo(null);
        etiqueta.setVisible(true);
        if(etiqueta.status){
            reportes.imprimir(estudiante.getV_cedula(), "notas");
        }
        new Verificacion().setVisible(true);
        etiqueta.monedero.status = false;
        etiqueta.dispose();
        dispose();
    }//GEN-LAST:event_calificacionesJButtonActionPerformed

    private void paraleloJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paraleloJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paraleloJTextFieldActionPerformed

    private void identidadJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identidadJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identidadJTextFieldActionPerformed

    private void jornadaJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jornadaJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jornadaJTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Estudiante estudiante = new Estudiante("fddfdsfsdf","sdfd", "dsfdfdsfsdfsdf", "ddasdasdasdasdasdasdasdasdasdsadasdfdsfdsfdsfsdf","sdfdsfdsfsdfdsfdsfsdf", "sdfsdfsdf", "sdfdsfdfsd");
               new Detalles(estudiante).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoJTextField;
    private javax.swing.JButton calificacionesJButton;
    private javax.swing.JTextField carreraJTextField;
    private javax.swing.JButton certificadoJButton;
    private javax.swing.JTextField identidadJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jornadaJTextField;
    private javax.swing.JTextField nombreJTextField;
    private javax.swing.JTextField paraleloJTextField;
    private javax.swing.JButton salirJButton;
    private javax.swing.JTextField semestreJTextField;
    // End of variables declaration//GEN-END:variables

    private void initComponentsOverride() {
       this.setExtendedState(JFrame.MAXIMIZED_BOTH);
       this.setLocationRelativeTo(null);
       this.getContentPane().setBackground(Color.WHITE);
       this.setIconImage(Config.iconDefault());
      
     
       nombreJTextField.setBorder(null);
       nombreJTextField.setBackground(new Color(0,0,0,0));
       apellidoJTextField.setBorder(null);
       apellidoJTextField.setBackground(new Color(0,0,0,0));
       identidadJTextField.setBorder(null);
       identidadJTextField.setBackground(new Color(0,0,0,0));
       carreraJTextField.setBorder(null);
       carreraJTextField.setBackground(new Color(0,0,0,0));
       semestreJTextField.setBorder(null);
       semestreJTextField.setBackground(new Color(0,0,0,0));
       paraleloJTextField.setBorder(null);
       paraleloJTextField.setBackground(new Color(0,0,0,0));
       jornadaJTextField.setBorder(null);
       jornadaJTextField.setBackground(new Color(0,0,0,0));
       this.requestFocus();
       nombreJTextField.setText(estudiante.getV_nombres());
       apellidoJTextField.setText(estudiante.getV_apellidos());
       identidadJTextField.setText(estudiante.getV_cedula());
       carreraJTextField.setText(estudiante.getV_carrera());
       semestreJTextField.setText(estudiante.getV_nivel());
       paraleloJTextField.setText(estudiante.getV_paralelo());
       jornadaJTextField.setText(estudiante.getV_jornada());
       
    }
    
    private boolean getUndecorated(){
        return Boolean.valueOf(Config.getValue("undecorated"));
    }
}
