/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.gnu.monedero.gui;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.gnu.monedero.dao.DaoMysqlSsh;
import org.gnu.monedero.utils.Config;
import org.gnu.monedero.utils.JTextFieldLimit;

/**
 *
 * @author dizurieta
 */
public class Verificacion extends javax.swing.JFrame {

    /**
     * Creates new form Verificacion
     */
    public Verificacion() {
        initComponents();
        initComponentsOverride();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        identityJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        identityJTextField = new javax.swing.JTextField();
        botonesJPanel = new javax.swing.JPanel();
        oneJButton = new javax.swing.JButton();
        twoJButton = new javax.swing.JButton();
        threeJButton = new javax.swing.JButton();
        findJButton = new javax.swing.JButton();
        fourJButton = new javax.swing.JButton();
        fiveJButton = new javax.swing.JButton();
        sixJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        sevenJButton = new javax.swing.JButton();
        eightJButton = new javax.swing.JButton();
        nineJButton = new javax.swing.JButton();
        deleteJButton = new javax.swing.JButton();
        null1JButton = new javax.swing.JButton();
        zeroJButton = new javax.swing.JButton();
        null2JButton = new javax.swing.JButton();
        null3JButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setUndecorated(getUndecorated());
        getContentPane().setLayout(null);

        identityJPanel.setLayout(new java.awt.GridLayout(1, 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("IDENTIDAD ");
        jLabel1.setToolTipText("");
        identityJPanel.add(jLabel1);

        identityJTextField.setEditable(false);
        identityJTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        identityJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        identityJTextField.setOpaque(false);
        identityJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identityJTextFieldActionPerformed(evt);
            }
        });
        identityJPanel.add(identityJTextField);

        getContentPane().add(identityJPanel);
        identityJPanel.setBounds(580, 330, 340, 30);

        botonesJPanel.setLayout(new java.awt.GridLayout(4, 4));

        oneJButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        oneJButton.setText("1");
        oneJButton.setToolTipText(null);
        oneJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        oneJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneJButtonActionPerformed(evt);
            }
        });
        botonesJPanel.add(oneJButton);

        twoJButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        twoJButton.setText("2");
        twoJButton.setToolTipText(null);
        twoJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        twoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoJButtonActionPerformed(evt);
            }
        });
        botonesJPanel.add(twoJButton);

        threeJButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        threeJButton.setText("3");
        threeJButton.setToolTipText(null);
        threeJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        threeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeJButtonActionPerformed(evt);
            }
        });
        botonesJPanel.add(threeJButton);

        findJButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        findJButton.setToolTipText(null);
        findJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        findJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findJButtonActionPerformed(evt);
            }
        });
        botonesJPanel.add(findJButton);

        fourJButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fourJButton.setText("4");
        fourJButton.setToolTipText(null);
        fourJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fourJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourJButtonActionPerformed(evt);
            }
        });
        botonesJPanel.add(fourJButton);

        fiveJButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fiveJButton.setText("5");
        fiveJButton.setToolTipText(null);
        fiveJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fiveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveJButtonActionPerformed(evt);
            }
        });
        botonesJPanel.add(fiveJButton);

        sixJButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sixJButton.setText("6");
        sixJButton.setToolTipText(null);
        sixJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sixJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixJButtonActionPerformed(evt);
            }
        });
        botonesJPanel.add(sixJButton);

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        backJButton.setToolTipText(null);
        backJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        botonesJPanel.add(backJButton);

        sevenJButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sevenJButton.setText("7");
        sevenJButton.setToolTipText(null);
        sevenJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sevenJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenJButtonActionPerformed(evt);
            }
        });
        botonesJPanel.add(sevenJButton);

        eightJButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        eightJButton.setText("8");
        eightJButton.setToolTipText(null);
        eightJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eightJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightJButtonActionPerformed(evt);
            }
        });
        botonesJPanel.add(eightJButton);

        nineJButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nineJButton.setText("9");
        nineJButton.setToolTipText(null);
        nineJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nineJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineJButtonActionPerformed(evt);
            }
        });
        botonesJPanel.add(nineJButton);

        deleteJButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deleteJButton.setToolTipText(null);
        deleteJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJButtonActionPerformed(evt);
            }
        });
        botonesJPanel.add(deleteJButton);

        null1JButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        null1JButton.setToolTipText(null);
        botonesJPanel.add(null1JButton);

        zeroJButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        zeroJButton.setText("0");
        zeroJButton.setToolTipText(null);
        zeroJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        zeroJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroJButtonActionPerformed(evt);
            }
        });
        botonesJPanel.add(zeroJButton);

        null2JButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        null2JButton.setToolTipText(null);
        botonesJPanel.add(null2JButton);

        null3JButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        null3JButton.setToolTipText(null);
        botonesJPanel.add(null3JButton);

        getContentPane().add(botonesJPanel);
        botonesJPanel.setBounds(580, 370, 340, 220);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/gnu/monedero/gui/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 0, 1490, 900);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fiveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveJButtonActionPerformed
        // TODO add your handling code here:
        identityJTextField.setText(identityJTextField.getText().concat("5"));
    }//GEN-LAST:event_fiveJButtonActionPerformed

    private void identityJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identityJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identityJTextFieldActionPerformed

    private void oneJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneJButtonActionPerformed
        // TODO add your handling code here:
        identityJTextField.setText(identityJTextField.getText().concat("1"));
    }//GEN-LAST:event_oneJButtonActionPerformed

    private void twoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoJButtonActionPerformed
        // TODO add your handling code here:
        identityJTextField.setText(identityJTextField.getText().concat("2"));
    }//GEN-LAST:event_twoJButtonActionPerformed

    private void threeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeJButtonActionPerformed
        // TODO add your handling code here:
        identityJTextField.setText(identityJTextField.getText().concat("3"));
    }//GEN-LAST:event_threeJButtonActionPerformed

    private void fourJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourJButtonActionPerformed
        // TODO add your handling code here:
        identityJTextField.setText(identityJTextField.getText().concat("4"));
    }//GEN-LAST:event_fourJButtonActionPerformed

    private void sixJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixJButtonActionPerformed
        // TODO add your handling code here:
        identityJTextField.setText(identityJTextField.getText().concat("6"));
    }//GEN-LAST:event_sixJButtonActionPerformed

    private void sevenJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenJButtonActionPerformed
        // TODO add your handling code here:
        identityJTextField.setText(identityJTextField.getText().concat("7"));
    }//GEN-LAST:event_sevenJButtonActionPerformed

    private void eightJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightJButtonActionPerformed
        // TODO add your handling code here:
        identityJTextField.setText(identityJTextField.getText().concat("8"));
    }//GEN-LAST:event_eightJButtonActionPerformed

    private void nineJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineJButtonActionPerformed
        // TODO add your handling code here:
        identityJTextField.setText(identityJTextField.getText().concat("9"));
    }//GEN-LAST:event_nineJButtonActionPerformed

    private void zeroJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroJButtonActionPerformed
        // TODO add your handling code here:
        identityJTextField.setText(identityJTextField.getText().concat("0"));
    }//GEN-LAST:event_zeroJButtonActionPerformed

    private void deleteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJButtonActionPerformed
        // TODO add your handling code here:
        identityJTextField.setText("");
    }//GEN-LAST:event_deleteJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        if (identityJTextField.getText().length() > 0)
            identityJTextField.setText(identityJTextField.getText().substring(0,identityJTextField.getText().length()-1));
    }//GEN-LAST:event_backJButtonActionPerformed

    private void findJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findJButtonActionPerformed
        // TODO add your handling code here:
        loadDatos();
    }//GEN-LAST:event_findJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Verificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Verificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Verificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Verificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Verificacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JPanel botonesJPanel;
    private javax.swing.JButton deleteJButton;
    private javax.swing.JButton eightJButton;
    private javax.swing.JButton findJButton;
    private javax.swing.JButton fiveJButton;
    private javax.swing.JButton fourJButton;
    private javax.swing.JPanel identityJPanel;
    private javax.swing.JTextField identityJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton nineJButton;
    private javax.swing.JButton null1JButton;
    private javax.swing.JButton null2JButton;
    private javax.swing.JButton null3JButton;
    private javax.swing.JButton oneJButton;
    private javax.swing.JButton sevenJButton;
    private javax.swing.JButton sixJButton;
    private javax.swing.JButton threeJButton;
    private javax.swing.JButton twoJButton;
    private javax.swing.JButton zeroJButton;
    // End of variables declaration//GEN-END:variables

    
    private void initComponentsOverride() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.white);
        this.setIconImage(Config.iconDefault());
        identityJTextField.requestFocus();
        identityJPanel.setBackground(Color.white);
        botonesJPanel.setBackground(Color.white);
        identityJTextField.setDocument(new JTextFieldLimit(20));
        Icons();
        
    }
    public void Icons(){
        
        String pathFindIcon = Config.pathImage().concat("find.png");
        Image imageFindIcon  = new ImageIcon(pathFindIcon).getImage();
        imageFindIcon = imageFindIcon.getScaledInstance(39, 39, java.awt.Image.SCALE_SMOOTH);
        findJButton.setIcon(new ImageIcon(imageFindIcon));
        
        
        String pathBackIcon = Config.pathImage().concat("backspaces.png");
        Image imageBackIcon  = new ImageIcon(pathBackIcon).getImage();
        imageBackIcon = imageBackIcon.getScaledInstance(39, 39, java.awt.Image.SCALE_SMOOTH);
        backJButton.setIcon(new ImageIcon(imageBackIcon));
        
        String pathDeleteIcon = Config.pathImage().concat("delete.png");
        Image imageDeleteIcon  = new ImageIcon(pathDeleteIcon).getImage();
        imageDeleteIcon = imageDeleteIcon.getScaledInstance(39, 39, java.awt.Image.SCALE_SMOOTH);
        deleteJButton.setIcon(new ImageIcon(imageDeleteIcon));
        
    } 

    private void loadDatos() {
        DaoMysqlSsh daoMysqlSsh = new DaoMysqlSsh();
        if (daoMysqlSsh.getValidacion(identityJTextField.getText().trim())){
            new Detalles(daoMysqlSsh.getEstudiante()).setVisible(true);
            this.setVisible(false);
            this.dispose();
        }else{
            Config.message(this, "Usuario no registrado", "INFORMATIVO", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private boolean getUndecorated(){
        return Boolean.valueOf(Config.getValue("undecorated"));
    }

}
